<a href="https://colab.research.google.com/github/Pedroct06/Estudos-NN/blob/main/Treino3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader, TensorDataset
from sklearn.datasets import load_iris

In [63]:
df= pd.read_csv("IRIS.csv")

In [64]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [65]:
X = df.drop(['species'], axis=1)
y = df['species']

In [66]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [68]:
X_train

     sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [69]:
scaler = StandardScaler()
X_train_escalonado = scaler.fit_transform(X_train)
X_test_escalonado = scaler.transform(X_test)

In [70]:
X_train_escalonado_tensor = torch.from_numpy(X_train_escalonado).float()
X_test_escalonado_tensor = torch.from_numpy(X_test_escalonado).float()
y_train_tensor = torch.from_numpy(y_train).long()
y_test_tensor = torch.from_numpy(y_test).long()

In [71]:
train_dataset = TensorDataset(X_train_escalonado_tensor, y_train_tensor)

In [72]:
X_train_escalonado_tensor.shape

torch.Size([120, 4])

In [73]:
train_loader = DataLoader(train_dataset, batch_size=4,shuffle=True)

In [74]:
class NNIris(nn.Module):
  def __init__(self):
    super(NNIris, self).__init__()
    self.fc1 = nn.Linear(4, 8)
    self.fc2 = nn.Linear(8,16)
    self.fc3 = nn.Linear(16,8)
    self.fc4 = nn.Linear(8, 3)
    self.relu = nn.ReLU()

  def forward(self, x):
    x = self.relu(self.fc1(x))
    x = self.relu(self.fc2(x))
    x = self.relu(self.fc3(x))
    x = self.fc4(x)
    return x

In [75]:
model = NNIris()

In [76]:
criterio = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.001)

In [79]:
epochs = 30

for epoch in range(epochs):
  model.train()
  running_loss = 0.0
  for X_batch, y_batch in train_loader:
    optimizer.zero_grad()
    preds = model(X_batch)
    loss = criterio(preds, y_batch)

    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  print(f"Epoch {epoch+1}: Loss was {running_loss/ len(train_loader)}")

Epoch 1: Loss was 0.192995589474837
Epoch 2: Loss was 0.1910019502043724
Epoch 3: Loss was 0.18659364668031533
Epoch 4: Loss was 0.17711390435385208
Epoch 5: Loss was 0.1684924477090438
Epoch 6: Loss was 0.14300071525697908
Epoch 7: Loss was 0.13637499200801054
Epoch 8: Loss was 0.1306536602632453
Epoch 9: Loss was 0.12279300826291244
Epoch 10: Loss was 0.12777337686469156
Epoch 11: Loss was 0.1149857153960814
Epoch 12: Loss was 0.10700496472418308
Epoch 13: Loss was 0.10193359494054069
Epoch 14: Loss was 0.09594106517421702
Epoch 15: Loss was 0.09753873964461188
Epoch 16: Loss was 0.09377993792295455
Epoch 17: Loss was 0.08863636036403477
Epoch 18: Loss was 0.08942271413592001
Epoch 19: Loss was 0.08647002525006732
Epoch 20: Loss was 0.08682883790073295
Epoch 21: Loss was 0.0809476963011548
Epoch 22: Loss was 0.07678545591576645
Epoch 23: Loss was 0.07873140308850755
Epoch 24: Loss was 0.07416085544973612
Epoch 25: Loss was 0.08095051265942553
Epoch 26: Loss was 0.06943946964262675
Epoch 27: Loss was 0.06954453406700244
Epoch 28: Loss was 0.067347270816875
Epoch 29: Loss was 0.07378171699820087
Epoch 30: Loss was 0.06937685935990885

In [82]:
with torch.no_grad():
  model.eval()
  preds = model(X_test_escalonado_tensor)
  classes = torch.argmax(preds, dim=1)
  accuracy = (classes == y_test_tensor).float().mean()

print(f"Acurácia do modelo = {accuracy * 100:.2f}%.")

Acurácia do modelo = 100.00%.